### ISSUE TITLE
Project Wireframes

### ISSUE THREAD

**Issue by StephenB92** [StephenB92/team3-january-hackathon#2]

**Comment by tanisecarvalho** [comment]
Created desktop wireframes for Login, Sign Up, 404 page and 500 page.

![Image](https://user-images.githubusercontent.com/15631445/213880197-3b8f2d66-e119-4693-8691-496346ae85f1.png)
![Image](https://user-images.githubusercontent.com/15631445/213880198-22da2ddf-e5bf-4d36-9b95-74a0f1495dc4.png)
![Image](https://user-images.githubusercontent.com/15631445/213880195-9cd3e50b-dc8b-4574-87b7-8d10c618928c.png)
![Image](https://user-images.githubusercontent.com/15631445/213880196-6c00c54c-42e3-4c3b-9811-67b3a6ea9b9d.png)

**Comment by Niki-Tester** [comment]
LGTM 😄 👍

**Comment by tanisecarvalho** [comment]
Mobile wireframes for the pages above.

![Image](https://user-images.githubusercontent.com/15631445/213880834-2776f694-65e1-4197-8ed2-be95afd2b2d7.png)

**Comment by Niki-Tester** [comment]
These are looking good. 
If you could add to the repo. So that they can be added to the read me.

**Comment by vero-nika-2828** [comment]
Here we go.  Desktop wireframe view. I will add it to repo as well so I can update readme with Tenise's and my wireframes

![Financial_app_tream3_wireframe_page1_desktop 1](https://user-images.githubusercontent.com/110194097/213884375-2d1042f4-2500-42cf-b211-d427034af87d.PNG)

![Financial_app_tream3_wireframe_page2_desktop 1](https://user-images.githubusercontent.com/110194097/213884413-67a9dacf-c2f2-46a2-ad19-68141c74a0f6.PNG)

![Financial_app_tream3_wireframe_page3_desktop 1](https://user-images.githubusercontent.com/110194097/213884429-e00b59a2-ad5d-4724-97aa-fbb7b7f63a4a.PNG)

**Comment by vero-nika-2828** [comment]
![Financial_app_tream3_wireframe_page1 1](https://user-images.githubusercontent.com/110194097/213884483-1022102f-8d9e-4496-835c-af3e77087294.PNG)

![Financial_app_tream3_wireframe_page2 1](https://user-images.githubusercontent.com/110194097/213884499-d553e384-6660-497f-bfde-f0e6a860f601.PNG)
![Financial_app_tream3_wireframe_page3_savingpage 1](https://user-images.githubusercontent.com/110194097/213884523-236100d6-b778-4a8e-af5b-30c9be4f0756.PNG)
